name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Trusted Signing
        uses: Azure/trusted-signing-action@v0.3.17
        with:
          azure-tenant-id: ${{ secrets.TrustedSigningTenantID }}
          azure-client-id: ${{ secrets.TrustedSigningSigningClientId }}
          azure-client-secret: ${{ secrets.TrustedSigningSigningSecret}}
          endpoint: ${{ secrets.TrustedSigningEndPoint }}
          trusted-signing-account-name: ${{ secrets.TrustedSigningAccountName}}
          certificate-profile-name: ${{ secrets.TrustedSigningCertificateProfile}}
          files-folder: ${{ github.workspace }}
          files-folder-filter: 'ps1,psm1,psd1,dll'
          files-folder-recurse: true
          files-folder-depth: 5

      
        
