# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Trusted Signing
        uses: Azure/trusted-signing-action@v0.3.17
        with:
          azure-tenant-id: ${{ secrets.TrustedSigningTenantID }}
          azure-client-id: ${{ secrets.TrustedSigningSigningClientId }}
          azure-client-secret: ${{ secrets.TrustedSigningSigningSecret}}
          endpoint: ${{ secrets.TrustedSigningEndPoint }}
          trusted-signing-account-name: ${{ secrets.TrustedSigningAccountName}}
          certificate-profile-name: ${{ secrets.TrustedSigningCertificateProfile}}
          files-folder: ${{ github.workspace }}
          files-folder-filter: 'ps1,psm1,psd1,dll'
          files-folder-recurse: true
          files-folder-depth: 5
        
